### ISSUE TITLE
publish `numba_mpi` on conda

### ISSUE THREAD

**Issue by david-zwicker** [atmos-cloud-sim-uj/numba-mpi#27]
Would it be possible to publish the package on `conda` as well as on `pypi`? I would like to use the package in my [`py-pde` project](https://github.com/zwicker-group/py-pde) and `conda` is a convenient way of installing many packages together, e.g., in an HPC environment.

**Comment by slayoo** [comment]
Yes, let's plan on making a PR to https://github.com/conda-forge/staged-recipes/ which will start our way into conda! Stay tuned...

**Comment by slayoo** [comment]
And here it is: https://github.com/conda-forge/staged-recipes/pull/20199

**Comment by david-zwicker** [comment]
Looks great! I'm looking forward to using this package in my work.

**Comment by david-zwicker** [comment]
Looks like [`numba-mpi` is available on condo-forge](https://anaconda.org/conda-forge/numba-mpi) now. Thanks for the great work!
