### ISSUE TITLE
Does not support Intel MPI

### ISSUE THREAD

**Issue by DManowitz** [atmos-cloud-sim-uj/numba-mpi#40]
I tried to import numba_mpi, but got the following error:

 ```
 File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\numba_mpi\__init__.py", line 4, in <module>
    from .mpi import Operator, allreduce, initialized, rank, recv, send, size
  File "...\lib\site-packages\numba_mpi\mpi.py", line 34, in <module>
    libmpi = ctypes.CDLL(LIB)
  File "...\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

I see that in mpi.py you try to load msmpi.dll.  However, this is not the only possible library for MPI.  For example, Intel makes an MPI library available (see the Intel Conda channel, for example), which is what I have installed.

**Comment by abulenok** [comment]
https://github.com/atmos-cloud-sim-uj/numba-mpi/pull/41
Solution on its way 🚀

**Comment by slayoo** [comment]
Now available on pypi.org as v0.16: https://pypi.org/project/numba-mpi/0.16/, will soon be also released on conda-forge
Please let us know if that helps

**Comment by slayoo** [comment]
conda package ready: https://github.com/conda-forge/numba-mpi-feedstock/pull/3

**Comment by slayoo** [comment]
Since #47 we are running the tests also with Intel MPI on CI, what confirms that it works! Closing.
